sudo: false

dist: xenial
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

virtualenv:
  system_site_packages: true

install:
  - pip install -r requirements.txt

script:
  - python setup.py test
